site_name: "Workshop: Equinix Labs LBaaS CPEM CAPP"

repo_url: https://github.com/equinix-labs/equinix-metal-load-balancer-cpem-capp-workshop
repo_name: equinix-labs/equinix-metal-load-balancer-cpem-capp-workshop
edit_uri: blob/main/docs

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md

  - Parts:
      - 1. Account and API Key: parts/1-account-api-key.md
      - 2. Deploy Cluster: parts/2-deploy-cluster.md
      - 3. Deploy App: parts/3-deploy-app.md
      - Conclusion: parts/conclusion.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    logo: simple/equinixmetal
  favicon: images/favicon.ico

  features:
    - navigation.top
    - search.highlight
    - navigation.footer
    - content.code.copy
    - navigation.expand

extra:
  social:
    - icon: simple/equinixmetal
      link: https://deploy.equinix.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@equinixmetal
    - icon: fontawesome/brands/github
      link: https://github.com/equinix-labs
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@EquinixDevelopers

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.keys
